name: Build Flutter App

on:
  push:
    tags: 
      - 'v*.*.*'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=${{ steps.setup-java.outputs.java-home }}" >> $GITHUB_ENV

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --split-per-abi

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Install GitHub CLI
      run: sudo apt-get install gh
  
    - name: Create Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
        build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk \
        build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
        build/app/outputs/flutter-apk/app-x86_64-release.apk \
        --title "Release ${{ github.ref_name }}" \
        --notes "Release notes for ${{ github.ref_name }}"